# Generated by Django 5.2.5 on 2025-09-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_bool', 'Can change book'), ('can_delete_book', 'Can delete book')]},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('hard', 'Hardcover'), ('soft', 'Softcover')], default='soft', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=979138475839, max_length=13, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationship_app.author'),
        ),
    ]
